package com.online.exam.tb;

// Generated 2015-1-22 23:19:06 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ExamPaperItemTb generated by hbm2java
 */
@SuppressWarnings("serial")
@Entity
@Table(name = "exam_paper_item_tb", catalog = "exam")
public class ExamPaperItemTb implements java.io.Serializable {

	private String id;
	private ItemTb itemTb;
	private ExamPaperTb examPaperTb;

	public ExamPaperItemTb() {
	}

	public ExamPaperItemTb(String id, ItemTb itemTb, ExamPaperTb examPaperTb) {
		this.id = id;
		this.itemTb = itemTb;
		this.examPaperTb = examPaperTb;
	}

	@Id
	@Column(name = "ID", unique = true, nullable = false, length = 36)
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ITEM_NUM", nullable = false)
	public ItemTb getItemTb() {
		return this.itemTb;
	}

	public void setItemTb(ItemTb itemTb) {
		this.itemTb = itemTb;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "EXAM_PAPER_NUM", nullable = false)
	public ExamPaperTb getExamPaperTb() {
		return this.examPaperTb;
	}

	public void setExamPaperTb(ExamPaperTb examPaperTb) {
		this.examPaperTb = examPaperTb;
	}

}
