package com.online.exam.tb;

// Generated 2015-1-22 23:19:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * ItemTb generated by hbm2java
 */
@SuppressWarnings({"serial","rawtypes"})
@Entity
@Table(name = "item_tb", catalog = "exam")
public class ItemTb implements java.io.Serializable {

	private String itemNum;
	private String title;
	private String option;
	private String type;
	private Integer difficulty;
	private String answer;
	private Date addTime;
	private Set examPaperItemTbs = new HashSet(0);

	public ItemTb() {
	}

	public ItemTb(String itemNum, String title, String option, String type,
			Integer difficulty, String answer) {
		this.itemNum = itemNum;
		this.title = title;
		this.option = option;
		this.type = type;
		this.difficulty = difficulty;
		this.answer = answer;
	}

	public ItemTb(String itemNum, String title, String option, String type,
			Integer difficulty, String answer, Date addTime, Set examPaperItemTbs) {
		this.itemNum = itemNum;
		this.title = title;
		this.option = option;
		this.type = type;
		this.difficulty = difficulty;
		this.answer = answer;
		this.addTime = addTime;
		this.examPaperItemTbs = examPaperItemTbs;
	}

	@Id
	@Column(name = "ITEM_NUM", unique = true, nullable = false, length = 36)
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
	public String getItemNum() {
		return this.itemNum;
	}

	public void setItemNum(String itemNum) {
		this.itemNum = itemNum;
	}

	@Column(name = "TITLE", nullable = false, length = 640)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "OPTION", nullable = false, length = 640)
	public String getOption() {
		return this.option;
	}

	public void setOption(String option) {
		this.option = option;
	}

	@Column(name = "TYPE", nullable = false, length = 4)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	@Column(name = "DIFFICULTY", nullable = false)
	public Integer getDifficulty() {
		return this.difficulty;
	}

	public void setDifficulty(Integer difficulty) {
		this.difficulty = difficulty;
	}

	@Column(name = "ANSWER", nullable = false, length = 1)
	public String getAnswer() {
		return this.answer;
	}

	public void setAnswer(String answer) {
		this.answer = answer;
	}

	@Column(name = "ADD_TIME", length = 19)
	public Date getAddTime() {
		return this.addTime;
	}

	public void setAddTime(Date addTime) {
		this.addTime = addTime;
	}

	@OneToMany(cascade = { CascadeType.ALL },fetch = FetchType.LAZY, mappedBy = "itemTb", targetEntity=ExamPaperItemTb.class)
	public Set getExamPaperItemTbs() {
		return this.examPaperItemTbs;
	}

	public void setExamPaperItemTbs(Set examPaperItemTbs) {
		this.examPaperItemTbs = examPaperItemTbs;
	}

}
