package com.online.exam.tb;

// Generated 2015-1-22 23:19:06 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * StudentTb generated by hbm2java
 */
@SuppressWarnings({"serial","rawtypes"})
@Entity
@Table(name = "student_tb", catalog = "exam")
public class StudentTb implements java.io.Serializable {

	private String stuId;
	private String stuNum;
	private String name;
	private String grade;
	private String loginPassword;
	private Date createTime;
	private Set scoreTbs = new HashSet(0);

	public StudentTb() {
	}

	public StudentTb(String stuId, String stuNum, String name, String grade,
			String loginPassword) {
		this.stuId = stuId;
		this.stuNum = stuNum;
		this.name = name;
		this.grade = grade;
		this.loginPassword = loginPassword;
	}

	public StudentTb(String stuId, String stuNum, String name, String grade,
			String loginPassword, Date createTime, Set scoreTbs) {
		this.stuId = stuId;
		this.stuNum = stuNum;
		this.name = name;
		this.grade = grade;
		this.loginPassword = loginPassword;
		this.createTime = createTime;
		this.scoreTbs = scoreTbs;
	}

	@Id
	@Column(name = "STU_ID", unique = true, nullable = false, length = 36)
	@GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid")
	public String getStuId() {
		return this.stuId;
	}

	public void setStuId(String stuId) {
		this.stuId = stuId;
	}

	@Column(name = "STU_NUM", nullable = false, length = 36)
	public String getStuNum() {
		return this.stuNum;
	}

	public void setStuNum(String stuNum) {
		this.stuNum = stuNum;
	}

	@Column(name = "NAME", nullable = false, length = 20)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "GRADE", nullable = false, length = 64)
	public String getGrade() {
		return this.grade;
	}

	public void setGrade(String grade) {
		this.grade = grade;
	}

	@Column(name = "LOGIN_PASSWORD", nullable = false, length = 36)
	public String getLoginPassword() {
		return this.loginPassword;
	}

	public void setLoginPassword(String loginPassword) {
		this.loginPassword = loginPassword;
	}

	@Column(name = "CREATE_TIME", length = 19)
	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "studentTb",targetEntity=ScoreTb.class)
	public Set getScoreTbs() {
		return this.scoreTbs;
	}

	public void setScoreTbs(Set scoreTbs) {
		this.scoreTbs = scoreTbs;
	}

}
